apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: knode-ingress
spec:
  defaultBackend:
    service:
      name: knode
      port:
        number: 80
---

apiVersion: v1
kind: Service
metadata:
  name: knode
spec:
  selector:
    app: knode
  ports:
    - port: 80
      targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: knode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: knode
  template:
    metadata:
      labels:
        app: knode
    spec:
      containers:
        - name: knode
          image: learnk8s/knote-js:1.0.0
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/dev
          imagePullPolicy: Always
