
apiVersion: v1
kind: Service
metadata:
  name: knode
spec:
  selector:
    app: knode
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: knode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: knode
  template:
    metadata:
      labels:
        app: knode
    spec:
      containers:
        - name: knode
          image: learnk8s/knote-js:1.0.0
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/dev
          imagePullPolicy: Always
